server:
  port: 8001
  servlet:
    context-path: /es
spring:
  application:
    name: es-server
  elasticsearch:
    uris: 192.168.60.130:9200
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8767/eureka/eureka